### ISSUE TITLE
Plugin source code is out of sync with Unity scripts and DLL

### ISSUE THREAD

**Issue by augiem** [mrayy/mrayGStreamerUnity#12]
The source code for the UnityGStreamerPlugin.dll is not compatible with the Unity scripts. The VS project has been updated, but the Unity scripts and the Unity DLL have not. Therefore, I cannot actually even get the source code to the compiled GStreamerUnityPlugin.dll.

For example:
Note the existence of mray_gst_customPlayerGrabFrame in the DllImport calls here. This is called in code.

https://raw.githubusercontent.com/mrayy/mrayGStreamerUnity/master/Unity/UnityTests/Assets/GStreamerUnity/Scripts/GstCustomPlayer.cs

When building the source code for the DLL, no such function exists. It is missing from PlayersAPI.c and can't be found when searching the sollution. This makes the the DLL built with the current source code not work with the Unity scripts.
https://raw.githubusercontent.com/mrayy/mrayGStreamerUnity/master/Plugin/sources/PlayersAPI.cpp

**Comment by mrayy** [comment]
Just fixed the issue, the frame grabbing function was generalized to: mray_gst_playerGrabFrame().
