### ISSUE TITLE
I cant load x64 lib

### ISSUE THREAD

**Issue by felchs** [mrayy/mrayGStreamerUnity#33]
Hello I downloaded the lib put into an example project.

I managed to change x86 to x64 putting the pre-compile libs

Assets\Plugins\x86_64\GStreamerUnityPlugin.dll
Assets\Plugins\x86_64\UnityWebcam.dll

from mrayGStreamerUnity-master\Unity\UnityTests\Assets\Plugins

but I'm getting:
```

Failed to load mrayGStreamer Library:GStreamerUnityPlugin
UnityEngine.Debug:LogError (object)
GStreamerCore:Ref () (at Assets/GStreamerUnity/Scripts/GStreamerCore.cs:50)
GstCustomTexture:Initialize () (at Assets/GStreamerUnity/Scripts/GstCustomTexture.cs:48)
GStreamerTest1:Start () (at Assets/GStreamerUnity/Tests/GStreamerTest1.cs:20)
```

and

```
DllNotFoundException: GStreamerUnityPlugin
GStreamerCore.get_IsActive () (at Assets/GStreamerUnity/Scripts/GStreamerCore.cs:41)
GStreamerCore.Ref () (at Assets/GStreamerUnity/Scripts/GStreamerCore.cs:53)
GstCustomTexture.Initialize () (at Assets/GStreamerUnity/Scripts/GstCustomTexture.cs:48)
GStreamerTest1.Start () (at Assets/GStreamerUnity/Tests/GStreamerTest1.cs:20)
```

I setup  GST_SDK_PATH= C:\gstreamer\1.0\x86_64\

Unity version 2020.3.8f1

**Comment by mrayy** [comment]
You will need to add to PATH environment variable gstreamer runtime binaries path as well:
C:\gstreamer\1.0\x86_64\bin

**Comment by felchs** [comment]
yes it solved the problem! thank you!
