### ISSUE TITLE
still get Dll not Found error on both unity 2020 & 2021

### ISSUE THREAD

**Issue by miroc99** [mrayy/mrayGStreamerUnity#39]
I  follow the README and previous issue comment steps, install both runtime and dev gstreamer on C:\gstreamer\1.0
and add all the needed environment variables,gstreamer command line tool is working but I still get this error when in unity.

os: windows 10 home
gstreamer : 1.16.2 msvc 
unity : 2020.3.25f1 & 2021.2.2f1
![image](https://user-images.githubusercontent.com/52696812/175495569-b4d91410-a7a4-4514-9a66-f47ef3ef47a4.png)

My system  environment variables setting
![image](https://user-images.githubusercontent.com/52696812/175495730-8bc27ee7-8cae-4840-a888-1411f11bd02d.png)
![image](https://user-images.githubusercontent.com/52696812/175495774-5714627b-094b-46a5-9f7c-c16991bc7921.png)

soultion already try
change form mingw to msvc (also delete cache %USERPROFILE%\AppData\Local\Microsoft\Windows\INetCache\gstreamer-1.0\registry.x86_64.bin mention in #18  )

**Comment by mrayy** [comment]
Could you confirm that gstreamer is detected by running the following via command line:
gst-launch-1.0 --version

if it works and reports gstreamer version, then next please make sure to have C++ redistributables latest via this:

https://aka.ms/vs/17/release/vc_redist.x64.exe

One last thing, Please don't use (GStreamerPlugin.unitypackage) as I haven't updated it yet.

Let me know how the above goes

**Comment by miroc99** [comment]
Thanks for your quick reply,I directly open this project in unity and install C++ redistributables from the link you provided.
Now it works like a charm!

**Comment by mrayy** [comment]
Great, I will close this ticket then
