### ISSUE TITLE
I can't run my project, it says Dll can't be found

### ISSUE THREAD

**Issue by QiaoJingjing** [mrayy/mrayGStreamerUnity#41]
Hi~ 
I read other issues, checked the Path in the system variable, and I can run the gstreamer command through the command line. In addition, I also changed the unity version to 2021.3.4.1, but it still can't run, and I can't find it using depends. to gstreamer's dll, but I don't know how to fix it。
System: Windows11
![image](https://user-images.githubusercontent.com/19723593/186563734-b8410a9d-1071-4995-870c-878d5537b77f.png)
![image](https://user-images.githubusercontent.com/19723593/186563754-c26b215e-2ea6-4e9d-a055-130034d4b0ab.png)

**Comment by QiaoJingjing** [comment]
I've fixed this issue because if you've already installed vc_redist, you need to uninstall and reinstall it

But, I have a new question, I can through cmd run this command,but it not run in project, how to setup it
![image](https://user-images.githubusercontent.com/19723593/186840703-e1715ce6-6ba8-4e54-8991-ede004a4f601.png)

gst-launch-1.0.exe -v udpsrc port=1935 caps = "application/x-rtp, media=video, clock-rate=90000, encoding-name=H264, payload=96" ! rtph264depay ! avdec_h264 ! autovideosink


![image](https://user-images.githubusercontent.com/19723593/186840882-f901b893-5fd0-4f85-8ab6-0c2ae1c9b789.png)

**Comment by mrayy** [comment]
Great hearing you resolved the issue. About your follow up question, I noticed your pipeline in C# is incorrect. Your C# pipeline translates into something like:
udpsrc port=1935 ! caps="application/x-rtp"! rtpjitterbuffer ! ....
As you can see, the "caps" shouldn't have ! before it, also, the last " after x-rtp doesn't have a space with the following !

**Comment by QiaoJingjing** [comment]
Yes , it right , i have run it successfully！！！
In addition, I would like to ask you how to set the resolution of the camera sampling





---- Replied Message ----
| From | MHD Yamen ***@***.***> |
| Date | 08/26/2022 18:12 |
| To | ***@***.***> |
| Cc | ***@***.******@***.***> |
| Subject | Re: [mrayy/mrayGStreamerUnity] I can't run my project, it says Dll can't be found (Issue #41) |

Great hearing you resolved the issue. About your follow up question, I noticed your pipeline in C# is incorrect. Your C# pipeline translates into something like:
udpsrc port=1935 ! caps="application/x-rtp"! rtpjitterbuffer ! ....
As you can see, the "caps" shouldn't have ! before it, also, the last " after x-rtp doesn't have a space with the following !

**Comment by QiaoJingjing** [comment]
Hi , i try build and run this project . but it can't playing

**Comment by QiaoJingjing** [comment]
![image](https://user-images.githubusercontent.com/19723593/188583133-8bfa7162-6808-402d-8b0c-1185bbe62ed8.png)

**Comment by QiaoJingjing** [comment]
Maybe it's a matter of the number of bits I posted? It is currently 32 bits

**Comment by QiaoJingjing** [comment]
I solved it！it is  nead build for 64 bits

**Comment by egemenertugrul** [comment]
> 

Which version of vcredist_x64 did you reinstall? I resinstalled the 2010 and 2013 versions and it did not work.

**Comment by egemenertugrul** [comment]
> I've fixed this issue because if you've already installed vc_redist, you need to uninstall and reinstall it
> 
> But, I have a new question, I can through cmd run this command,but it not run in project, how to setup it ![image](https://user-images.githubusercontent.com/19723593/186840703-e1715ce6-6ba8-4e54-8991-ede004a4f601.png)
> 
> gst-launch-1.0.exe -v udpsrc port=1935 caps = "application/x-rtp, media=video, clock-rate=90000, encoding-name=H264, payload=96" ! rtph264depay ! avdec_h264 ! autovideosink
> 
> ![image](https://user-images.githubusercontent.com/19723593/186840882-f901b893-5fd0-4f85-8ab6-0c2ae1c9b789.png)
> 
> it's my pusher command gst-launch-1.0.exe -v ksvideosrc device-index=1 ! decodebin ! x264enc pass=qual quantizer=20 tune=zerolatency ! rtph264pay ! udpsink host=localhost port=1935 qos=false sync=false

Which version of vcredist_x64 did you reinstall? I resinstalled the 2010 and 2013 versions and it did not work.

**Comment by QiaoJingjing** [comment]
![image](https://user-images.githubusercontent.com/19723593/197466775-9c44d680-f5c5-439d-bfe5-7e8901c6e8ed.png)
this version , if you run for building , maybe nead set 64bit build.

**Comment by QiaoJingjing** [comment]
The problem has been solved
