### ISSUE TITLE
Compile plugin in Release mode

### ISSUE THREAD

**Issue by ahmadreza-hadidi** [mrayy/mrayGStreamerUnity#58]
Hi everybody
@mrayy thank you for your great work
But please recompile your plugin in "Release" mode. the current dll in your git repository is compiled in debug mode
So when you want to distribute the application to other ones you have to install Visual Studio or copy these Dlls in plugin directory. Its the problem that many peoples say the Dll cannot load

![image](https://github.com/mrayy/mrayGStreamerUnity/assets/5848329/744179d5-2ce9-4f09-adc3-b4a915c72e48)
Please note the "d" suffix in dependency tree

**Comment by mrayy** [comment]
Thank you for pointing this out, I recompiled in release and merged
