### ISSUE TITLE
what are the troubleshooting steps for "Failed to load .... Plugin.dll"  ?

### ISSUE THREAD

**Issue by mutantbob** [mrayy/mrayGStreamerUnity#7]
I tried following the steps in the README.md (except for the recompilation in step 4) and had to reboot a couple of times.

But when I open Test 1 in Unity and try to run it I get errors in the console:

```
Plugins: Failed to load 'Assets/Plugins/x86_64/GStreamerUnityPlugin.dll' with error 'The specified module could not be found.
'.
GstBaseTexture:Initialize() (at Assets/GStreamerUnity/Scripts/GstBaseTexture.cs:92)
GstBaseTexture:Initialize() (at Assets/GStreamerUnity/Scripts/GstBaseTexture.cs:88)
CustomPipelinePlayer:Start() (at Assets/GStreamerUnity/Components/CustomPipelinePlayer.cs:26)
```
I can see the .dll in the Assets/Plugins/x86_64 directory, but something is causing it to fail.

Is it the fact that I'm using Visual Studio 2017 instead of 2013 (I tried installing the runtime for 2017 first, but when that didn't let me run the scene I fetched 2013 and did a "repair").  Is it the fact that I'm running Unity 2017.3.1f1 instead of 5.6.3 or whatever?  How do I test that the gstreamer runtime is properly installed?  The %PATH% appears to include the correct directory ( d:\gstreamer\1.0\x86_64\bin  is where it got installed )

**Comment by zhangdiyu** [comment]
same issues

**Comment by lincode** [comment]
same issues

**Comment by mrayy** [comment]
Usually when such an error is reported (Plugin failed to load) its usually due to GStreamer installation and PATH Environment Variable.

Could you reinstall GStreamer into c:\, and make sure its "Full Installation" with all components installed.
Double check your PATH environment variable that it includes:
c:\gstreamer\1.0\x86_64\bin

And then reload Unity and run the samples again.

**Comment by mrayy** [comment]
If the issue still persisted, could you use a dependency walker (e.g. https://www.dependencywalker.com/) and load the plugin into it. 
Could you provide here the list of the missing dlls that would show.

**Comment by johnny-wang16** [comment]
Missing dlls from dependency's worker:
GLIB-2.0.DLL
GOBJECT-2.0-0.DLL
GSTAPP-1.0-0.DLL
GSTAUDIO-1.0-0.DLL
GSTREAMER-1.0-0.DLL
GSTVIDEO-1.0-0.DLL

My system user PATH variable:  C:\gstreamer\1.0\x86_64\lib\gstreamer-1.0  C:\gstreamer\1.0\x86_64\bin

**Comment by johnny-wang16** [comment]
Im not sure if there's anything else to do after installing gstreamer and clone the repo. Do I need to re compile the GStreamerUnityPlugin. DLL ?

**Comment by mrayy** [comment]
> Missing dlls from dependency's worker:
> GLIB-2.0.DLL
> GOBJECT-2.0-0.DLL
> GSTAPP-1.0-0.DLL
> GSTAUDIO-1.0-0.DLL
> GSTREAMER-1.0-0.DLL
> GSTVIDEO-1.0-0.DLL
> 
> My system user PATH variable: C:\gstreamer\1.0\x86_64\bin

These missing dlls means the system couldn’t locate them in PATH variable or couldn’t load them for some reason.

Could you double check the path exists and these dlls are inside?

C:\gstreamer\1.0\x86_64\bin

**Comment by johnny-wang16** [comment]
I can see these files:
GLIB-2.0.pdb
GOBJECT-2.0-0.pdb
GSTAPP-1.0-0.pdb
GSTAUDIO-1.0-0.pdb
GSTREAMER-1.0-0.pdb
GSTVIDEO-1.0-0.pdb
in C:\gstreamer\1.0\x86_64\bin . but I didn't find the .dll files in it. I uninstalled gstreamer and installed it again but I still couldnt find those 6 dlls. However, I found the following dlls inside the directory.
libglib-2.0-0.dll
libgobject-2.0-0.dll
libgstaudio-1.0-0.dll
libgstreamer-1.0-0.dll
libgstvideo-1.0-0.dll

I installed gstreamer accodring to this [video](https://www.youtube.com/watch?v=_JZNCypATOY). Basically install the runtime version and then the devel version and select "complete" installation for both version. I tried the command gst-launch-1.0 videotestsrc ! autovideosink and it worked.

**Comment by johnny-wang16** [comment]
Is it ok if i just change the name of the dlls ? for example, can i just change "libglib-2.0-0.dll" to "glib-2.0-0.dll" and put it in the Assets/Plugins folder ?

**Comment by mrayy** [comment]
Thats weird to have the libraries with "lib" prefix. Which version of GStreamer are you using?
I have tested it with 1.16.2 and the library naming is correct without "lib" prefix.

You can check the version in command line:
gst-launch-1.0 --version

**Comment by johnny-wang16** [comment]
This is what I got with gst-launch-1.0:
```
WARNING: no real random source present!
gst-launch-1.0 version 1.16.2
GStreamer 1.16.2
Unknown package origin
```
i uninstalled gstreamer and installed again. It still has the lib prefix tho.

**Comment by johnny-wang16** [comment]
i resolved my issue. turns out that i installed different compiler versions for devel and runtime.  make sure they are both msvc

**Comment by sourabmaity** [comment]
@mrayy close this issue.
